name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./Dockerfile"
          target: "/opt/asetp/frontend"

      - name: Copy docker file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./default.conf"
          target: "/opt/asetp/frontend"

      - name: Copy config file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./dist"
          target: "/opt/asetp/frontend"

      - name: Build and Run Docker on server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd /opt/asetp/frontend
              docker build -t asetp_frontend .
              docker stop asetp_frontend_container || true
              docker rm asetp_frontend_container || true
              docker run -d --name asetp_frontend_container -p 8001:8000 asetp_frontend
              docker image prune -f
              docker cp asetp_frontend_container:/etc ./test
              docker cp asetp_frontend_container:/opt/asetp/frontCode ./test
              cat test/etc/nginx/nginx.conf
              ls test/frontCode
              
